apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo-app-deployment
spec:
  replicas: 4
  strategy:
    canary: 
      canaryService: rollout-canary-preview
      stableService: rollout-canary-active
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      trafficRouting:
        smi: 
          trafficSplitName: rollout-example-traffic-split 
          rootService: rollout-canary-all-traffic 
      steps:
        - setWeight: 10
        - setCanaryScale:
            weight: 25
        - pause: {duration: 5m}
        - setWeight: 33
        - setCanaryScale:
            weight: 50
        - pause: {duration: 5m}
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 4 # delay starting analysis run until setWeight: 10%
        args:
        - name: service-name
          value: canary-demo-app       
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-demo-app
  template:
    metadata:
      labels:
        app: canary-demo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        linkerd.io/inject: enabled  
    spec:
      containers:
      - name: canary-demo-app-container
        image: flavioaiello/canary-demo-app:{{CF_SHORT_REVISION}}         
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
